In [5]:
import psycopg2

In [6]:
import pandas as pd

In [7]:
from sqlalchemy import create_engine

In [13]:
alchemyengine = create_engine('postgresql+psycopg2://OLD_DB_URL')

In [14]:
db_connection = alchemyengine.connect()

In [16]:
df = pd.read_sql("SELECT * FROM \"person\"", db_connection);

In [17]:
display(df)

,person_id,name,surname,ssn,email,password,role_id,username
0,3,Greta,Borg,None,None,wl9nk23a,1,borg
1,4,Per,Strand,19671212-1211,per@strand.kth.se,None,2,None
2,19,erik,erik,12345,erik@erik.se,erik123,2,erik2
3,21,hash,hash,12381948,hash@salt.se,$2a$10$w.rr7hdGmfP5Tz.ODNzB8OmEIbacWHH7fzMoEfI...,2,serr
4,36,lucas,villarroel,12345,lucasvi@kth.se,$2a$10$yS7u1Y2hRzmg9kHo1gFlTO2/iyIJS051oeKWBKF...,2,lucas
5,23,Test,TestBoi,12345,test@testmail.com,$2a$10$T1yqPOFJPG01gNRhx7T/8.4ZLCU5s34U02.hTZB...,2,UPDATEEEBABBYYY
6,24,test,testboi,12345,test2@testmail.com,$2a$10$fdm./Rzh3i1GKa4cdmQ/4OYcSX.P8Th1VWncrZT...,2,testboii
7,39,Arsene,Wenger,194910221111,arsweng@mail.com,$2a$10$xsvdXYcS8jNfzwXK0GW8yeJzntVVIWV.23c.EFE...,2,ArsenolSucks
8,40,Klas,3ngberg,k312,notanemail,$2a$10$jn6YGZ44KV3jT9XR01UfTuLjAx55gQ60qLLtS3L...,2,kalas_klas
9,43,Klas,Klaengberg,9991231,actual_mail@hotmail.com,$2a$10$.FbG5Sh.bv0YeR2cUKXsC.U44O9Rbrie3x1G95n...,2,kalas_klas420
10,44,Pusha,T,12344556,pushat@kth.se,$2a$10$n.VYXu5tuaaB6OZmUPU2GumU7ZSTKbe2ch5EtwY...,2,PUSH
11,45,Farsan,Baloo,19931202,baloo@kth.se,$2a$10$Bkz7n6gldY/J8r3ek/CjfOq/2yKkbGKenlqW7VK...,2,Baloo420

In [ ]:
# To transfer data to new db:
#
# alchemyengine = create_engine('postgresql+psycopg2://YOUR_DB_URI')
# pg_connection = alchemyengine.connect()
#df.to_sql('person', pg_connection)
#pg_connection.close()

In [18]:
db_connection.close()